update: CatWrt.v23.8.mt798x
update: CatWrt.v23.8.mt798x

diff --git a/package/base-files/files/usr/bin/catwrt-update b/package/base-files/files/usr/bin/catwrt-update
--- a/package/base-files/files/usr/bin/catwrt-update
+++ b/package/base-files/files/usr/bin/catwrt-update
@@ -1,88 +1,64 @@
 #!/bin/bash
 ###
- # @Author: timochan
- # @Date: 2023-02-03 19:45:22
- # @LastEditors: timochan,miaoermua
- # @LastEditTime: 2023-4-17 14:05:21
- # @FilePath: /miaoermua/catwrt-update/bash/catwrt-update_6.1.sh
-### 
+# @Author: timochan
+# @Date: 2023-02-03 19:45:22
+# @LastEditors: timochan
+# @LastEditTime: 2023-08-08 13:35:15
+# @FilePath: /catwrt-update/bash/main/catwrt-update.sh
+###
+
+API_URL="https://api.miaoer.xyz/api/v2/snippets/catwrt/update"
+VERSION_FILE="/etc/catwrt_release"
+
 remote_error() {
-    echo "Remote $1 get failed, please check your network!"
+    echo "Remote $1 get failed for arch: $arch_self, please check your network!"
     exit 1
 }
 local_error() {
-    echo "Local $1 get failed, please check your /etc/catwrt_release!"
+    echo "Local $1 get failed, please check your /etc/catwrt-release!"
     exit 1
 }
-get_remote_version(){
+get_remote_hash() {
     arch_self=$1
-    if [ $arch_self == "x86_64" ]; then
-    version_remote=`curl https://api.miaoer.xyz/api/v2/snippets/catwrt/check_update_DEV | jq -r '.version_amd64'`
-    elif [ $arch_self == "aarch64" ]; then
-    version_remote=`curl https://api.miaoer.xyz/api/v2/snippets/catwrt/check_update_DEV | jq -r '.version_rkarm'`
-    elif [ $arch_self == "mips" ]; then
-    version_remote=`curl https://api.miaoer.xyz/api/v2/snippets/catwrt/check_update_DEV | jq -r '.version_wireless'`
-    fi
+    version_remote=$(curl -s "$API_URL" | jq -r ".$arch_self.version")
+    hash_remote=$(curl -s "$API_URL" | jq -r ".$arch_self.hash")
 
-    if [ $arch_self == "x86_64" ]; then
-        hash_remote=`curl https://api.miaoer.xyz/api/v2/snippets/catwrt/check_update_DEV | jq -r '.hash_amd64'`
-    elif [ $arch_self == "aarch64" ]; then
-        hash_remote=`curl https://api.miaoer.xyz/api/v2/snippets/catwrt/check_update_DEV | jq -r '.hash_rkarm'`
-    elif [ $arch_self == "mips" ]; then
-        hash_remote=`curl https://api.miaoer.xyz/api/v2/snippets/catwrt/check_update_DEV | jq -r '.hash_wireless'`
-    else 
-        echo "Your system is not supported!"
-        exit 1
-    fi
-
-    if [ $? -ne 0 ] || [ -z $hash_remote ]; then
-        remote_error "hash"
-        exit 1
+    if [ $? -ne 0 ] || [ -z "$version_remote" ] || [ -z "$hash_remote" ]; then
+        remote_error "version or hash"
     fi
 }
-get_arch_and_remote_version() {
-    arch=`uname -m`
-    if [ $? -ne 0 ] || [ -z $arch ]; then
-        echo "Arch get failed, Please contact the firmware author!"
-        exit 1
-    fi
-
-    get_remote_version $arch
-
-}
-get_local_version(){
-
-    if [ ! -f /etc/catwrt_release ]; then
+init() {
+    if [ ! -f "$VERSION_FILE" ]; then
         local_error "version file"
-        exit 1
     fi
-    version_local=`cat /etc/catwrt_release | grep 'ver' | cut -d '=' -f 2`
-    hash_local=`cat /etc/catwrt_release | grep 'hash' | cut -d '=' -f 2`
 
-
+    version_local=$(grep 'version' "$VERSION_FILE" | cut -d '=' -f 2)
+    hash_local=$(grep 'hash' "$VERSION_FILE" | cut -d '=' -f 2)
+    source_local=$(grep 'source' "$VERSION_FILE" | cut -d '=' -f 2)
+    arch_local=$(grep 'arch' "$VERSION_FILE" | cut -d '=' -f 2)
 }
-contrast_version(){
-    if [ $version_remote == $version_local ] && [ $hash_remote == $hash_local ]; then
-        echo "======================================"
+contrast_version() {
+    if [ "$version_remote" == "$version_local" ] && [ "$hash_remote" == "$hash_local" ]; then
+        echo "================================"
         echo "Your CatWrt is up to date!"
-        echo "======================================"
+        echo "================================"
     else
-        echo "======================================"
-        echo "Your CatWrt is not up to date, You should upgrade it!"
+        echo "================================"
+        echo "Your CatWrt is out of date, you should upgrade it!"
         echo "You can visit 'https://www.miaoer.xyz/posts/network/catwrt' to get more information!"
-        echo "======================================"
+        echo "================================"
     fi
 }
-print_version(){
-        echo "Local  Version : $version_local"
-        echo "Remote Version : $version_remote"
-        echo "Local  Hash : $hash_local"
-        echo "Remote Hash : $hash_remote"
-        echo "======================================"
+print_version() {
+    echo "Local  Version : $version_local"
+    echo "Remote Version : $version_remote"
+    echo "Local  Hash    : $hash_local"
+    echo "Remote Hash    : $hash_remote"
+    echo "================================"
 }
-main(){
-    get_arch_and_remote_version
-    get_local_version
+main() {
+    init
+    get_remote_hash "$arch_local"
     contrast_version
     print_version
 }
